#include <iostream>
#include <fstream>

#include "json_reader.h"
#include "request_handler.h"
#include "transport_catalogue.h"


using namespace std;
using namespace transport::catalogue;
using namespace renderer;

int main() {
    istringstream input("  {\n"
                        "      \"base_requests\": [\n"
                        "          {\n"
                        "              \"is_roundtrip\": true,\n"
                        "              \"name\": \"297\",\n"
                        "              \"stops\": [\n"
                        "                  \"Biryulyovo Zapadnoye\",\n"
                        "                  \"Biryulyovo Tovarnaya\",\n"
                        "                  \"Universam\",\n"
                        "                  \"Biryulyovo Zapadnoye\"\n"
                        "              ],\n"
                        "              \"type\": \"Bus\"\n"
                        "          },\n"
                        "          {\n"
                        "              \"is_roundtrip\": false,\n"
                        "              \"name\": \"635\",\n"
                        "              \"stops\": [\n"
                        "                  \"Biryulyovo Tovarnaya\",\n"
                        "                  \"Universam\",\n"
                        "                  \"Prazhskaya\"\n"
                        "              ],\n"
                        "              \"type\": \"Bus\"\n"
                        "          },\n"
                        "          {\n"
                        "              \"latitude\": 55.574371,\n"
                        "              \"longitude\": 37.6517,\n"
                        "              \"name\": \"Biryulyovo Zapadnoye\",\n"
                        "              \"road_distances\": {\n"
                        "                  \"Biryulyovo Tovarnaya\": 2600\n"
                        "              },\n"
                        "              \"type\": \"Stop\"\n"
                        "          },\n"
                        "          {\n"
                        "              \"latitude\": 55.587655,\n"
                        "              \"longitude\": 37.645687,\n"
                        "              \"name\": \"Universam\",\n"
                        "              \"road_distances\": {\n"
                        "                  \"Biryulyovo Tovarnaya\": 1380,\n"
                        "                  \"Biryulyovo Zapadnoye\": 2500,\n"
                        "                  \"Prazhskaya\": 4650\n"
                        "              },\n"
                        "              \"type\": \"Stop\"\n"
                        "          },\n"
                        "          {\n"
                        "              \"latitude\": 55.592028,\n"
                        "              \"longitude\": 37.653656,\n"
                        "              \"name\": \"Biryulyovo Tovarnaya\",\n"
                        "              \"road_distances\": {\n"
                        "                  \"Universam\": 890\n"
                        "              },\n"
                        "              \"type\": \"Stop\"\n"
                        "          },\n"
                        "          {\n"
                        "              \"latitude\": 55.611717,\n"
                        "              \"longitude\": 37.603938,\n"
                        "              \"name\": \"Prazhskaya\",\n"
                        "              \"road_distances\": {},\n"
                        "              \"type\": \"Stop\"\n"
                        "          }\n"
                        "      ],\n"
                        "      \"render_settings\": {\n"
                        "          \"bus_label_font_size\": 20,\n"
                        "          \"bus_label_offset\": [\n"
                        "              7,\n"
                        "              15\n"
                        "          ],\n"
                        "          \"color_palette\": [\n"
                        "              \"green\",\n"
                        "              [\n"
                        "                  255,\n"
                        "                  160,\n"
                        "                  0\n"
                        "              ],\n"
                        "              \"red\"\n"
                        "          ],\n"
                        "          \"height\": 200,\n"
                        "          \"line_width\": 14,\n"
                        "          \"padding\": 30,\n"
                        "          \"stop_label_font_size\": 20,\n"
                        "          \"stop_label_offset\": [\n"
                        "              7,\n"
                        "              -3\n"
                        "          ],\n"
                        "          \"stop_radius\": 5,\n"
                        "          \"underlayer_color\": [\n"
                        "              255,\n"
                        "              255,\n"
                        "              255,\n"
                        "              0.85\n"
                        "          ],\n"
                        "          \"underlayer_width\": 3,\n"
                        "          \"width\": 200\n"
                        "      },\n"
                        "      \"routing_settings\": {\n"
                        "          \"bus_velocity\": 40,\n"
                        "          \"bus_wait_time\": 6\n"
                        "      },\n"
                        "      \"stat_requests\": [\n"
                        "          {\n"
                        "              \"id\": 1,\n"
                        "              \"name\": \"297\",\n"
                        "              \"type\": \"Bus\"\n"
                        "          },\n"
                        "          {\n"
                        "              \"id\": 2,\n"
                        "              \"name\": \"635\",\n"
                        "              \"type\": \"Bus\"\n"
                        "          },\n"
                        "          {\n"
                        "              \"id\": 3,\n"
                        "              \"name\": \"Universam\",\n"
                        "              \"type\": \"Stop\"\n"
                        "          },\n"
                        "          {\n"
                        "              \"from\": \"Biryulyovo Zapadnoye\",\n"
                        "              \"id\": 4,\n"
                        "              \"to\": \"Universam\",\n"
                        "              \"type\": \"Route\"\n"
                        "          },\n"
                        "          {\n"
                        "              \"from\": \"Biryulyovo Zapadnoye\",\n"
                        "              \"id\": 5,\n"
                        "              \"to\": \"Prazhskaya\",\n"
                        "              \"type\": \"Route\"\n"
                        "          }\n"
                        "      ]\n"
                        "  }\n"
                        "  ");

    ifstream file_in("input.json");
    ofstream file_out("output.json");

    // main instance of TC
    TransportCatalogue transportCatalogue;

    // reading data
    JsonReader jsonReader;
    jsonReader.Load(file_in);

    // executing with handler
    transport::handlers::RequestHandler requestHandler(transportCatalogue);
    requestHandler.ExecuteQueries(jsonReader.GetStopQueries(), jsonReader.GetBusQueries());
    const auto r = requestHandler.ExecuteStats(jsonReader.GetStatRequests(), jsonReader);
    file_out << r;

    return 0;
}